// userlib_tcc.c - TinyCC-compatible wrapper for MicroNT userlib
#include "userlib.h"

__asm__(
".global _start\n"
"_start:\n"
"    mov %rdx, %r8\n"
"    mov %rcx, %rdx\n"
"    mov %rbx, %rcx\n"
"    sub $32, %rsp\n"
"    call main\n"
"    add $32, %rsp\n"
"    mov $2, %rax\n"
"    xor %rbx, %rbx\n"
"    int $0x80\n"
"    jmp .\n"

".global _tcc_start\n"
"_tcc_start:\n"
"    mov %rdx, %r8\n"
"    mov %rcx, %rdx\n"
"    mov %rbx, %rcx\n"
"    sub $32, %rsp\n"
"    call tcc_main_entry\n"
"    add $32, %rsp\n"
"    mov $2, %rax\n"
"    xor %rbx, %rbx\n"
"    int $0x80\n"
"    jmp .\n"

".global syscall0\n"
"syscall0:\n"
"    mov %rcx, %rax\n"
"    int $0x80\n"
"    ret\n"

".global syscall1\n"
"syscall1:\n"
"    push %rbx\n"
"    mov %rcx, %rax\n"
"    mov %rdx, %rbx\n"
"    int $0x80\n"
"    pop %rbx\n"
"    ret\n"

".global syscall2\n"
"syscall2:\n"
"    push %rbx\n"
"    mov %rcx, %rax\n"
"    mov %rdx, %rbx\n"
"    mov %r8, %rcx\n"
"    int $0x80\n"
"    pop %rbx\n"
"    ret\n"

".global syscall3\n"
"syscall3:\n"
"    push %rbx\n"
"    mov %rcx, %rax\n"
"    mov %rdx, %rbx\n"
"    mov %r8, %rcx\n"
"    mov %r9, %rdx\n"
"    int $0x80\n"
"    pop %rbx\n"
"    ret\n"

".global syscall4\n"
"syscall4:\n"
"    push %rbx\n"
"    push %rsi\n"
"    mov %rcx, %rax\n"
"    mov %rdx, %rbx\n"
"    mov %r8, %rcx\n"
"    mov %r9, %rdx\n"
"    mov 56(%rsp), %rsi\n"
"    int $0x80\n"
"    pop %rsi\n"
"    pop %rbx\n"
"    ret\n"

".global _setjmp\n"
"_setjmp:\n"
"    mov %rbx, (%rcx)\n"
"    mov %rsp, 8(%rcx)\n"
"    mov %rbp, 16(%rcx)\n"
"    mov %rdi, 24(%rcx)\n"
"    mov %rsi, 32(%rcx)\n"
"    mov %r12, 40(%rcx)\n"
"    mov %r13, 48(%rcx)\n"
"    mov %r14, 56(%rcx)\n"
"    mov %r15, 64(%rcx)\n"
"    mov (%rsp), %rax\n"
"    mov %rax, 72(%rcx)\n"
"    xor %rax, %rax\n"
"    ret\n"

".global longjmp\n"
"longjmp:\n"
"    mov (%rcx), %rbx\n"
"    mov 8(%rcx), %rsp\n"
"    mov 16(%rcx), %rbp\n"
"    mov 24(%rcx), %rdi\n"
"    mov 32(%rcx), %rsi\n"
"    mov 40(%rcx), %r12\n"
"    mov 48(%rcx), %r13\n"
"    mov 56(%rcx), %r14\n"
"    mov 64(%rcx), %r15\n"
"    mov 72(%rcx), %r8\n"
"    mov %r8, (%rsp)\n"
"    mov %rdx, %rax\n"
"    test %rax, %rax\n"
"    jnz 1f\n"
"    mov $1, %rax\n"
"1:\n"
"    ret\n"
);

// Include the rest of the C implementation
#include "userlib.c"
